# -*- coding: utf-8 -*-
"""Exercicio2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9fbmRnRG_4wVwP5OHJzliCB9T0Q81aw
"""

print(5 / 2) #divisão

print(7 * 4 + 2) #sem precedência em operadores seguidos em  linha 

print((7 * 4) + 2) #precedencia  do operador multiplicador

print(7 * (4 + 2)) #precedencia do operador multiplicador

print(2 ** 3)  #potenciação

print(2 ** 3 ** 4) #potenciação

print(2 ** -3 ** 4) #potenciação

print(5 % 2)   # resto da divisão

print(6 % 2)   # resto da divisão

print(7 % 2)   # resto da divisão

print(8 % 2)  # resto da divisão

print(5 + 1) #adição

print(5.0 + 1) #adição

#Importar biblioteca math.

import math   
 
print("Log value: ", 5 * math.log10(100) - 8 ** 2)

print("Pi value: ",math.pi)

print("Sin value: ",math.sin(math.pi / 2 ))

print("Cos value: ", math.cos(math.pi / 4 ))