# -*- coding: utf-8 -*-
"""Exercício1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWURR9OV1YO1xpnU1vQmBKpsQqDoiWMY
"""

A=1

True

print(type(A))

B= 5 / 2

2.5

False

print(type(B))

C = 5 + 3j

print(type(C))

#A função type() é usada para retornar a classe (tipo de dados) de um objeto Python específico ou um novo objeto de tipo que é criado a partir dos argumentos fornecidos.
#A função print() é usada para imprimir strings, objetos e caracteres.